#!/usr/bin/env python3
"""Build the single-file FixBuddy executable from maintained source files."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parent.parent
CORE = ROOT / "src" / "core.sh"
TUI = ROOT / "src" / "tui.py"
WIZARD = ROOT / "src" / "wizard.sh"
OUTPUT = ROOT / "fixbuddy"
TUI_END = "__FIXBUDDY_TUI_SOURCE_20260927_END__"
WIZARD_END = "__FIXBUDDY_WIZARD_SOURCE_20260927_END__"
HELP_END = "__FIXBUDDY_HELP_20260927_END__"


def core_help(core: str) -> str:
    lines = []
    for line in core.splitlines()[1:]:
        if line == "set -uo pipefail":
            break
        if line.startswith("# "):
            line = line[2:]
        elif line == "#":
            line = ""
        lines.append(line)
    return "\n".join(lines).rstrip() + "\n"


def render() -> bytes:
    core = CORE.read_text(encoding="utf-8")
    tui = TUI.read_text(encoding="utf-8")
    wizard = WIZARD.read_text(encoding="utf-8")
    help_text = core_help(core)
    for marker in (TUI_END, WIZARD_END, HELP_END):
        if any(marker == line for source in (core, tui, wizard, help_text)
               for line in source.splitlines()):
            raise ValueError(f"embedded source collides with heredoc marker {marker}")
    wrapper = f'''#!/usr/bin/env bash
# Generated by scripts/build.py. Edit src/core.sh, src/tui.py or src/wizard.sh.

fixbuddy_tui_source() {{ cat <<'{TUI_END}'
{tui.rstrip()}
{TUI_END}
}}

fixbuddy_wizard_source() {{ cat <<'{WIZARD_END}'
{wizard.rstrip()}
{WIZARD_END}
}}

fixbuddy_help_source() {{ cat <<'{HELP_END}'
{help_text.rstrip()}
{HELP_END}
}}

fixbuddy_self="$(cd "$(dirname "$0")" && pwd -P)/$(basename "$0")"
if [ "$#" -eq 0 ]; then
  if [ -t 0 ] && [ -t 1 ] && command -v python3 >/dev/null 2>&1; then
    FIXBUDDY_SELF="$fixbuddy_self" python3 -c "$(fixbuddy_tui_source)"
    exit $?
  fi
  if [ -t 0 ] && [ -t 1 ]; then
    FIXBUDDY_SELF="$fixbuddy_self" bash -c "$(fixbuddy_wizard_source)"
    exit $?
  fi
  printf 'fixbuddy needs a terminal with no arguments; use fixbuddy run for config-only CLI mode.\\n' >&2
  exit 2
fi
case "$1" in
  --tui)
    shift
    command -v python3 >/dev/null 2>&1 || {{ printf 'Python 3 is required for the terminal UI.\\n' >&2; exit 2; }}
    FIXBUDDY_SELF="$fixbuddy_self" python3 -c "$(fixbuddy_tui_source)" "$@"
    exit $? ;;
  --catalog-worker)
    FIXBUDDY_SELF="$fixbuddy_self" python3 -c "$(fixbuddy_tui_source)" "$@"
    exit $? ;;
  --wizard)
    shift
    FIXBUDDY_SELF="$fixbuddy_self" bash -c "$(fixbuddy_wizard_source)" "$@"
    exit $? ;;
  run) shift ;;
esac
FIXBUDDY_EMBEDDED_HELP="$(fixbuddy_help_source)"

{core.rstrip()}
'''
    return wrapper.encode("utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if fixbuddy differs from source")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_bytes() != expected:
            print("fixbuddy bundle differs from maintained source", file=sys.stderr)
            return 1
        print("fixbuddy bundle matches source")
        return 0
    temporary = OUTPUT.with_name(".fixbuddy.build.tmp")
    if temporary.exists():
        raise FileExistsError(f"refusing to overwrite {temporary}")
    temporary.write_bytes(expected)
    os.chmod(temporary, 0o755)
    temporary.replace(OUTPUT)
    print(f"built {OUTPUT} ({len(expected)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
